<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Zend Framework Quickstart Application</title>
    <?php echo $this->headLink()->appendStylesheet('css/global.css') ?>
</head>
<body>
<div id="header">
    <div id="header-logo" style="float: left">
        <b>ZF Quickstart Application</b>
    </div>
    <div id="header-todolist">
        <a href="<?php echo $this->url(
            array('controller'=>'todolist'),
            'default',
            true) ?>">To-Do List</a>
    </div>
    <div id="header-forum">
        <a href="<?php echo $this->url(
            array('controller'=>'forum'),
            'default',
            true) ?>">Forum</a>

    </div>
    <div id="header-guestbook">
        <a href="<?php echo $this->url(
            array('controller'=>'guestbook'),
            'default',
            true) ?>">Guestbook</a>
    </div>
</div>
<?php echo $this->layout()->content ?>
</body>
</html>